// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9rmXe1bRAc33PqI8ZI6YwN4BjtoAkxQ',
    appId: '1:703191283452:web:7333bece4863f08a6b4979',
    messagingSenderId: '703191283452',
    projectId: 'task-manager-19052025',
    authDomain: 'task-manager-19052025.firebaseapp.com',
    storageBucket: 'task-manager-19052025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2_zg_nlG_uugwulbp8xGs-pF3gwyS6M',
    appId: '1:703191283452:android:f2d71d25b5d45e946b4979',
    messagingSenderId: '703191283452',
    projectId: 'task-manager-19052025',
    storageBucket: 'task-manager-19052025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPqRSYhfm59tLlUXsJMfSYX-ElpbBnuw',
    appId: '1:703191283452:ios:6a8c2fc4bc48fc0b6b4979',
    messagingSenderId: '703191283452',
    projectId: 'task-manager-19052025',
    storageBucket: 'task-manager-19052025.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPqRSYhfm59tLlUXsJMfSYX-ElpbBnuw',
    appId: '1:703191283452:ios:6a8c2fc4bc48fc0b6b4979',
    messagingSenderId: '703191283452',
    projectId: 'task-manager-19052025',
    storageBucket: 'task-manager-19052025.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm9rmXe1bRAc33PqI8ZI6YwN4BjtoAkxQ',
    appId: '1:703191283452:web:4df5cef235c31a5e6b4979',
    messagingSenderId: '703191283452',
    projectId: 'task-manager-19052025',
    authDomain: 'task-manager-19052025.firebaseapp.com',
    storageBucket: 'task-manager-19052025.firebasestorage.app',
  );
}
